sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t andyrozh/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true andyrozh/react-test npm test

after_success:
    - docker build -t andyrozh/multi-client ./client
    - docker build -t andyrozh/multi-nginx ./nginx
    - docker build -t andyrozh/multi-server ./server
    - docker build -t andyrozh/multi-worker ./worker
    # Take those images and push to docker-hub
    - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
    - docker push andyrozh/multi-client
    - docker push andyrozh/multi-nginx
    - docker push andyrozh/multi-server
    - docker push andyrozh/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-800288725902"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY